# Generated by Django 4.2.6 on 2023-10-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_skill_jobpost_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="type",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part Time"),
                    ("Internship", "Internship"),
                ],
                default="Full Time",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="description",
            field=models.TextField(),
        ),
    ]
