# Generated by Django 4.2.6 on 2023-10-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="files")),
            ],
        ),
    ]
